### ISSUE TITLE
Output missing \n on new server config between options

### ISSUE THREAD

**Issue by marneu** [fictivekin/wireguard#1]
venv: Python 3.8.10 (default, Sep 28 2021,16:10:42)
> OS: Ubuntu 20.04

Tried default from Quick Start just adding another interface name:
```
>>> from wireguard import Server
>>> server = Server('myvpnserver.com', '192.168.24.0/24', address='192.168.24.1', interface='wg22')
>>> server.config().write()
```
Expected behavior:
```
[Interface]
Address = 192.168.24.1/24
DNS = 
ListenPort = 51820
PrivateKey = nB/cWBL3Zug5+7UV0hcOLXQVuj6Mbjym2z3yhpfCoKk=
SaveConfig = false
PostUp = wg addconf %i /etc/wireguard/wg22-peers.conf
```

Error condition is:
```
[Interface]
Address = 192.168.24.1/24
DNS = 
ListenPort = 51820
PrivateKey = nB/cWBL3Zug5+7UV0hcOLXQVuj6Mbjym2z3yhpfCoKk=
SaveConfig = falsePostUp = wg addconf %i /etc/wireguard/wg22-peers.conf
```

**Comment by jnhmcknight** [comment]
Thanks @marneu! I'm not entirely sure how the problem occurs for you, but your solution is a good one, and I've noticed a couple other places that I'll use `os.linesep` in the config module.

**Comment by marneu** [comment]
@jnhmcknight: Nice, I saw you already updated PiPy.
