### ISSUE TITLE
How to pass a keypair (pubkey and privkey separately as kwargs) to the Server constructor?

### ISSUE THREAD

**Issue by xqly-stack** [fictivekin/wireguard#14]

**Comment by xqly-stack** [comment]
Something like:

````python
server = Server('myvpnserver.com', '192.168.24.0/24', address='192.168.24.1', privkey="...", pubkey="...")
````

If one would create the instance over and over again one would see that the privkey of the server is overwritten by a new one (A one-to-one relationship with the server and the peer). If there would be a possibility of passing already existing keys one would have a one-to-many relationship regarding the server and the peers, that would be the desirable result.

**Comment by jnhmcknight** [comment]
`Server` takes the same set of attributes that `Peer` takes, as it's a sub-class of `Peer` (for all allowed attributes, see: https://github.com/fictivekin/wireguard/blob/master/wireguard/peer.py#L83-L101). Thus, you would pass `private_key="<private-key-value>"`.

You _can_ also provide `public_key="<public-key-value>"` when you create the `Server` object, but it isn't absolutely necessary to do so, as the public key can be rebuilt from the private key value (see: https://github.com/fictivekin/wireguard/blob/master/wireguard/peer.py#L418-L430).

**Comment by xqly-stack** [comment]
Are there possibly any nuances that have to be taken into consideration while generating the keypair on your own (manually)? My project has 2 wireguard helper modules (wireguard and wireguard-lib) that cause a conflict, rendering the first module useless (CTRL + Click the link for optimal Result): 
https://github.com/viktor-gorinskiy/wireguard-lib/blob/main/README.md#:~:text=%3E%3E%3E%20from%20wireguard%20import%20Wireguard%0A%3E%3E%3E%20Wireguard().get_private_key%0A%27sBd8jkAY9Ht7wn%2Bq5iGbW4MfShgjdxB1s3oTJsttaHc%3D%27

**Comment by jnhmcknight** [comment]
There should be no nuances at this point, but to be clear, while we are not using the system's `wg` command, we are not _manually_ creating the public key. We are using [PyNaCL](https://pynacl.readthedocs.io/en/latest/) to [calculate it from the private key](https://github.com/fictivekin/wireguard/blob/master/wireguard/utils/keys.py#L13). PyNaCL is bindings to the system library `libsodium`, which handles the real public key calculation.

This method of public key calculation has been found to be reliable and consistently provides the same public key given the same private key as input on the various systems that we have used it on. However, it is entirely possible that an untested operating system's version of `libsodium` (or even `libc`) could have a minor bug that would make this method unreliable. It is also possible that future versions of Wireguard could change the method of public key calculation, which would make this method no longer valid. But in either of those two scenarios, then you would not even be able to use the `wg` command on the system as the peer system and the server system would be calculating the public key with different results and thus would never authenticate with each other to instantiate a connection.

Having said that, if you wish to provide both the `public_key` and the `private_key` to the `Server` or `Peer` instances, whatever you provide will be used to generate the wireguard config files. Thus, you are free to calculate the private key in whichever way that you prefer.
