### ISSUE TITLE
Applying in memory wireguard config without writing a file or encryption

### ISSUE THREAD

**Issue by noelashford** [fictivekin/wireguard#15]
Hello - I am looking for a way that I could do in memory wireguard configs that never hit disk (non persistent config - I have a valid use case) It is not ideal, but i would also accept ancrpted configs - far less ideal. Does WG take anything from memory natively or is there a mod out there ?

**Comment by jnhmcknight** [comment]
You could conceivably do that via the `wg` utility that WireGuard provides, but I believe that there are still some things that would need to be permanently set, specifically, the private key for the server. Past that, you can add and remove peers via the `wg` utility.

In terms of what this project could help with, there is an [`Interface`](https://github.com/fictivekin/wireguard/blob/master/wireguard/service.py) class that can run some commands directly against the running WireGuard instance (assuming appropriate user privileges). But not every capability has been included, as this project was never designed to fully replace the use of the `wg` utility and the WireGuard config files.

I would be interested to know the use-case for the solely in-memory WireGuard though.

**Comment by noelashford** [comment]
yeah i noticed int kernel implementation of it using 'set' allows everything except the keys to be passed in - I don't know why they never allowed the key to be passed in this way as well to the WG utility. My use case would see constantly changing interfaces / keys, i really need it to be non persistent as i would be pulling these from upstream / an API. With this being in the kernel, an API would be out of the question i assume.

Using LUKS to create somewhere secure to store my keys and doing a clean sweep of everything is def none ideal.

How does a VPN provider for example do this if they change the key each time? I assume they are cleaning it up each time on a client device such as a mobile.

**Comment by BowlesCR** [comment]
Would it work to write the file to a tempfs (ramdisk) and then use the `wg syncconf` functionality to load it into the kernel?

**Comment by noelashford** [comment]
Perhaps, I ended up making a LUKS crypt and opening and closing it as
needed WG wise and keeping control of the vault key from upstream.

The real desire which is hard as WG is in kernel would be an API for wire
guard that doesn't require files at all
