### ISSUE TITLE
Working with existing wireguard server setup

### ISSUE THREAD

**Issue by UrfinJuice11** [fictivekin/wireguard#8]
Hi, thanks for a great and useful project!

I wonder if I could work with an existing server setup.

The scenario:
I have a working wireguard server. I want to create a peer to the working server. If I create a new python session and a new server object there (with the keys of the original one) and try to create a new peer, then the file wg0-peers.conf will be overwritten with conf of the newly created peer. 

So, is there any way to pass current wg0.conf and wg0-peers.conf while creating Server object. 

p.s. Am I right that your lib only writes the config files and doesn't interact with wireguard process, so it is not able to restart the wg when adding a new client? If yes, could you please recommend a solution to reach the goal. Now thinking about **inotify** toolset to restart wg service every time the config files are modyfied.

Regards.

**Comment by jnhmcknight** [comment]
Unfortunately, no, you can't import from a Wireguard config file. Our approach to getting past that is explained in [this comment](https://github.com/fictivekin/wireguard/issues/6#issuecomment-1223433452).

As for the overwritten config file, you could create a minimal class to override `ServerConfig` which sets `filename` and `peers_filename` to something other than the interface name of the `Server` object. This functionality would likely be appreciated by other users, thus, if you wanted to submit a PR to allow using a different filename than the interface name (while defaulting to the interface name in the absence of a specific filename), we could look at including that in a release.

Now, for the service interaction, there are _some_ available in this package. It is not directly connected to the `Config`, `ServerConfig` nor the `Peer` objects, but it is connected to the `Server` object as `Server.service`. You could also instantiate the `Interface` object directly with the name of the interface. You can then interact with the service to a certain degree:

- show the interface status: `Interface.show()`
- stop/start/restart the interface: `Interface.stop()` / `Interface.start()` / `Interface.restart()`
- sync the running interface configuration with a different (or changed) config file: `Interface.sync(config_file_name)`
- add configuration settings (without changing existing ones) to a running interface: `Interface.add(config_file_name)`
- dump machine parse-able information about the running interface: `Interface.dump()`
- get a `dict` of configured peers' information from the running interface: `Interface.stats()`
- get a `list` of configured peers' public keys: `Interface.peers()`

Please note:
- neither `dump()`, nor `stats()` can return the private keys for the configured peers
- the user that you are running as must have sufficient privileges to use the `wg` and `wg-quick` commands

https://github.com/fictivekin/wireguard/blob/master/wireguard/service.py#L107

As an example of controlling an interface:

```python

# from a configured server instance
from wireguard import Server

server = Server(...)
server.service.start()
server.service.stats()

# or directly with the interface name
from wireguard.service import Interface

iface = Interface('wg0')
iface.start()
iface.stats()
```

Does that help at all?

**Comment by UrfinJuice11** [comment]
Hi, thanks for quick reply. 

About working with Current server - now creating server with statically declared keys and other parameters. So every time I want to create user I create  the same config. As a result the old config overwrites with the same one. 

About Interface - my fault, didn't dig the code enough. Also, found the CLI library. Actually, mb it would be a good step to mention all the opportunities in the manual?

One more newby question. Is there a function to delete a peer from wg0-peers.conf by his name (description) or at least his public key?

**Comment by jnhmcknight** [comment]
> mb it would be a good step to mention all the opportunities in the manual?

It most definitely would. This project would benefit from a proper documentation site.

> Is there a function to delete a peer from wg0-peers.conf by his name (description) or at least his public key?

There is not, but that is another great idea (added as #11).

However, while I've never tested it, since `server.peers` is a `set`, if you have the peer object that you'd like to remove from the `server.peers`, you should be able to do `server.peers.remove(unwanted_peer)`. Don't forget to also remove `server` from `unwanted_peer.peers` since they are linked in both directions.

**Comment by UrfinJuice11** [comment]
Yep, this works for me. Thanks
